spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/customerss
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
        format_sql: true
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      spring:
        jpa:
  port: 8888
