spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/customer
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true